version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./exports:/app/exports
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-in-production}
      - FLASK_ENV=production
    restart: unless-stopped
